/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { IRegionHeaderMenuItems } from "./components/shared/header/type";
import { ICategory } from "./components/pages/category/type";
import { MatchResults } from "@stencil/router";
import { IHero } from "./components/shared/app-hero/type";
export namespace Components {
    interface AppButton {
    }
    interface AppFooter {
        "attribution": string;
    }
    interface AppHeader {
        "logo": string;
        "menuItems": IRegionHeaderMenuItems[];
    }
    interface AppHero {
        "height"?: string;
        "imageSrc"?: string;
        "name"?: string;
        "overlay"?: boolean;
        "videoSrc"?: string;
    }
    interface AppRoot {
    }
    interface PageCategories {
        "categories": ICategory[];
        "header": string;
        "image"?: string;
    }
    interface PageCategory {
        "match": MatchResults;
    }
    interface PageHome {
        "banner": IHero;
        "content": string;
        "header": string;
        "hero": IHero;
        "highlights": {
    content: string;
    header: string;
  }[];
    }
}
declare global {
    interface HTMLAppButtonElement extends Components.AppButton, HTMLStencilElement {
    }
    var HTMLAppButtonElement: {
        prototype: HTMLAppButtonElement;
        new (): HTMLAppButtonElement;
    };
    interface HTMLAppFooterElement extends Components.AppFooter, HTMLStencilElement {
    }
    var HTMLAppFooterElement: {
        prototype: HTMLAppFooterElement;
        new (): HTMLAppFooterElement;
    };
    interface HTMLAppHeaderElement extends Components.AppHeader, HTMLStencilElement {
    }
    var HTMLAppHeaderElement: {
        prototype: HTMLAppHeaderElement;
        new (): HTMLAppHeaderElement;
    };
    interface HTMLAppHeroElement extends Components.AppHero, HTMLStencilElement {
    }
    var HTMLAppHeroElement: {
        prototype: HTMLAppHeroElement;
        new (): HTMLAppHeroElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLPageCategoriesElement extends Components.PageCategories, HTMLStencilElement {
    }
    var HTMLPageCategoriesElement: {
        prototype: HTMLPageCategoriesElement;
        new (): HTMLPageCategoriesElement;
    };
    interface HTMLPageCategoryElement extends Components.PageCategory, HTMLStencilElement {
    }
    var HTMLPageCategoryElement: {
        prototype: HTMLPageCategoryElement;
        new (): HTMLPageCategoryElement;
    };
    interface HTMLPageHomeElement extends Components.PageHome, HTMLStencilElement {
    }
    var HTMLPageHomeElement: {
        prototype: HTMLPageHomeElement;
        new (): HTMLPageHomeElement;
    };
    interface HTMLElementTagNameMap {
        "app-button": HTMLAppButtonElement;
        "app-footer": HTMLAppFooterElement;
        "app-header": HTMLAppHeaderElement;
        "app-hero": HTMLAppHeroElement;
        "app-root": HTMLAppRootElement;
        "page-categories": HTMLPageCategoriesElement;
        "page-category": HTMLPageCategoryElement;
        "page-home": HTMLPageHomeElement;
    }
}
declare namespace LocalJSX {
    interface AppButton {
    }
    interface AppFooter {
        "attribution"?: string;
    }
    interface AppHeader {
        "logo"?: string;
        "menuItems"?: IRegionHeaderMenuItems[];
    }
    interface AppHero {
        "height"?: string;
        "imageSrc"?: string;
        "name"?: string;
        "overlay"?: boolean;
        "videoSrc"?: string;
    }
    interface AppRoot {
    }
    interface PageCategories {
        "categories"?: ICategory[];
        "header"?: string;
        "image"?: string;
    }
    interface PageCategory {
        "match"?: MatchResults;
    }
    interface PageHome {
        "banner"?: IHero;
        "content"?: string;
        "header"?: string;
        "hero"?: IHero;
        "highlights"?: {
    content: string;
    header: string;
  }[];
    }
    interface IntrinsicElements {
        "app-button": AppButton;
        "app-footer": AppFooter;
        "app-header": AppHeader;
        "app-hero": AppHero;
        "app-root": AppRoot;
        "page-categories": PageCategories;
        "page-category": PageCategory;
        "page-home": PageHome;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-button": LocalJSX.AppButton & JSXBase.HTMLAttributes<HTMLAppButtonElement>;
            "app-footer": LocalJSX.AppFooter & JSXBase.HTMLAttributes<HTMLAppFooterElement>;
            "app-header": LocalJSX.AppHeader & JSXBase.HTMLAttributes<HTMLAppHeaderElement>;
            "app-hero": LocalJSX.AppHero & JSXBase.HTMLAttributes<HTMLAppHeroElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "page-categories": LocalJSX.PageCategories & JSXBase.HTMLAttributes<HTMLPageCategoriesElement>;
            "page-category": LocalJSX.PageCategory & JSXBase.HTMLAttributes<HTMLPageCategoryElement>;
            "page-home": LocalJSX.PageHome & JSXBase.HTMLAttributes<HTMLPageHomeElement>;
        }
    }
}
