/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { IField } from "./global/types";
import { RouterHistory } from "@stencil/router";
export namespace Components {
    interface AppField {
        "field": Partial<IField>;
    }
    interface AppFieldHtml {
        "fieldId": string;
    }
    interface AppForm {
        "action": string;
    }
    interface AppRoot {
    }
    interface AppSlugPair {
        "slug": string;
        "slugName": string;
    }
    interface PageCollectionEdit {
        "history": RouterHistory;
    }
    interface PageCollections {
    }
    interface PageHome {
    }
}
declare global {
    interface HTMLAppFieldElement extends Components.AppField, HTMLStencilElement {
    }
    var HTMLAppFieldElement: {
        prototype: HTMLAppFieldElement;
        new (): HTMLAppFieldElement;
    };
    interface HTMLAppFieldHtmlElement extends Components.AppFieldHtml, HTMLStencilElement {
    }
    var HTMLAppFieldHtmlElement: {
        prototype: HTMLAppFieldHtmlElement;
        new (): HTMLAppFieldHtmlElement;
    };
    interface HTMLAppFormElement extends Components.AppForm, HTMLStencilElement {
    }
    var HTMLAppFormElement: {
        prototype: HTMLAppFormElement;
        new (): HTMLAppFormElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAppSlugPairElement extends Components.AppSlugPair, HTMLStencilElement {
    }
    var HTMLAppSlugPairElement: {
        prototype: HTMLAppSlugPairElement;
        new (): HTMLAppSlugPairElement;
    };
    interface HTMLPageCollectionEditElement extends Components.PageCollectionEdit, HTMLStencilElement {
    }
    var HTMLPageCollectionEditElement: {
        prototype: HTMLPageCollectionEditElement;
        new (): HTMLPageCollectionEditElement;
    };
    interface HTMLPageCollectionsElement extends Components.PageCollections, HTMLStencilElement {
    }
    var HTMLPageCollectionsElement: {
        prototype: HTMLPageCollectionsElement;
        new (): HTMLPageCollectionsElement;
    };
    interface HTMLPageHomeElement extends Components.PageHome, HTMLStencilElement {
    }
    var HTMLPageHomeElement: {
        prototype: HTMLPageHomeElement;
        new (): HTMLPageHomeElement;
    };
    interface HTMLElementTagNameMap {
        "app-field": HTMLAppFieldElement;
        "app-field-html": HTMLAppFieldHtmlElement;
        "app-form": HTMLAppFormElement;
        "app-root": HTMLAppRootElement;
        "app-slug-pair": HTMLAppSlugPairElement;
        "page-collection-edit": HTMLPageCollectionEditElement;
        "page-collections": HTMLPageCollectionsElement;
        "page-home": HTMLPageHomeElement;
    }
}
declare namespace LocalJSX {
    interface AppField {
        "field"?: Partial<IField>;
    }
    interface AppFieldHtml {
        "fieldId"?: string;
    }
    interface AppForm {
        "action"?: string;
    }
    interface AppRoot {
    }
    interface AppSlugPair {
        "onSlugChange"?: (event: CustomEvent<{ slugName: string; slug: string }>) => void;
        "slug"?: string;
        "slugName"?: string;
    }
    interface PageCollectionEdit {
        "history"?: RouterHistory;
    }
    interface PageCollections {
    }
    interface PageHome {
    }
    interface IntrinsicElements {
        "app-field": AppField;
        "app-field-html": AppFieldHtml;
        "app-form": AppForm;
        "app-root": AppRoot;
        "app-slug-pair": AppSlugPair;
        "page-collection-edit": PageCollectionEdit;
        "page-collections": PageCollections;
        "page-home": PageHome;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-field": LocalJSX.AppField & JSXBase.HTMLAttributes<HTMLAppFieldElement>;
            "app-field-html": LocalJSX.AppFieldHtml & JSXBase.HTMLAttributes<HTMLAppFieldHtmlElement>;
            "app-form": LocalJSX.AppForm & JSXBase.HTMLAttributes<HTMLAppFormElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "app-slug-pair": LocalJSX.AppSlugPair & JSXBase.HTMLAttributes<HTMLAppSlugPairElement>;
            "page-collection-edit": LocalJSX.PageCollectionEdit & JSXBase.HTMLAttributes<HTMLPageCollectionEditElement>;
            "page-collections": LocalJSX.PageCollections & JSXBase.HTMLAttributes<HTMLPageCollectionsElement>;
            "page-home": LocalJSX.PageHome & JSXBase.HTMLAttributes<HTMLPageHomeElement>;
        }
    }
}
