/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppFieldHtml {
        "fieldId": string;
    }
    interface AppForm {
        "action": string;
    }
    interface AppRoot {
    }
    interface PageHome {
    }
}
declare global {
    interface HTMLAppFieldHtmlElement extends Components.AppFieldHtml, HTMLStencilElement {
    }
    var HTMLAppFieldHtmlElement: {
        prototype: HTMLAppFieldHtmlElement;
        new (): HTMLAppFieldHtmlElement;
    };
    interface HTMLAppFormElement extends Components.AppForm, HTMLStencilElement {
    }
    var HTMLAppFormElement: {
        prototype: HTMLAppFormElement;
        new (): HTMLAppFormElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLPageHomeElement extends Components.PageHome, HTMLStencilElement {
    }
    var HTMLPageHomeElement: {
        prototype: HTMLPageHomeElement;
        new (): HTMLPageHomeElement;
    };
    interface HTMLElementTagNameMap {
        "app-field-html": HTMLAppFieldHtmlElement;
        "app-form": HTMLAppFormElement;
        "app-root": HTMLAppRootElement;
        "page-home": HTMLPageHomeElement;
    }
}
declare namespace LocalJSX {
    interface AppFieldHtml {
        "fieldId"?: string;
    }
    interface AppForm {
        "action"?: string;
    }
    interface AppRoot {
    }
    interface PageHome {
    }
    interface IntrinsicElements {
        "app-field-html": AppFieldHtml;
        "app-form": AppForm;
        "app-root": AppRoot;
        "page-home": PageHome;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-field-html": LocalJSX.AppFieldHtml & JSXBase.HTMLAttributes<HTMLAppFieldHtmlElement>;
            "app-form": LocalJSX.AppForm & JSXBase.HTMLAttributes<HTMLAppFormElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "page-home": LocalJSX.PageHome & JSXBase.HTMLAttributes<HTMLPageHomeElement>;
        }
    }
}
